.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-BUNDLE" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-bundle\fR \-\- Bundle package dependencies
.
.SH "SYNOPSIS"
.
.nf
npm bundle
npm bundle destroy
npm bundle <cmd> <args>
.
.fi
.
.P
Run in a package folder\.
.
.SH "DESCRIPTION"
When run in a package folder, this command can be used to install
package dependencies into the \fBnode_modules\fR folder\.
.
.P
When the package is installed, it will read dependencies from the local
bundle \fIbefore\fR reading any dependencies that are already installed\.
.
.P
Furthermore, when installing, npm will not attempt to install
dependencies that already exist in the bundle\.
.
.P
To bundle all the dependencies of a given package, run \fBnpm bundle\fR
without any arguments\.
.
.P
To completely remove the bundle folder, run \fBnpm bundle destroy\fR\|\.
.
.P
To operate on the bundle packages, any npm command and arguments may be
passed to the \fBnpm bundle\fR command\.  For example, to install a package
into the bundle, you can do \fBnpm bundle install express\fR\|\.
.
.P
To list the packages in the bundle, do \fBnpm bundle ls\fR\|\.  To remove bundled
packages, do \fBnpm bundle remove <whatever>\fR\|\.  Et cetera\.
.
.P
In this way, a command like \fBnpm bundle install http://github\.com/user/project/tarball/master\fR can be used
to have a dependency that is not published on the npm registry\.  (It still
must contain a package\.json, though, of course\.)
.
.SH "CAVEATS"
Man pages are not installed by bundle\.
.
.P
Bins are installed, but not globally\.
.
.P
When a dependency is specified as a URL rather than a version range, it
is bundled with the package depending upon it\.
.
.SH "CONFIGURATION"
The bundle command itself is a proxy for \fBinstall\fR, or whichever command
is passed as the first argument\.  As such, it uses
the same configuration parameters as the commands it proxies,
but with the following temporary changes:
.
.IP "\(bu" 4
root: $PWD/node_modules/
.
.IP "\(bu" 4
binroot: $PWD/node_modules/\.bin
.
.IP "\(bu" 4
manroot: null
.
.IP "" 0
.
.P
See \fBnpm help config\fR for more information on these\.
