.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-CHANGELOG" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-changelog\fR \-\- Changes
.
.SH "HISTORY"
.
.IP "\(bu" 4
0\.0
.
.br
Lots of sketches and false starts\.  Abandoned a few times\.
.
.br
Core functionality established\.
.
.br
alpha\.
.
.IP "\(bu" 4
0\.1
.
.br
push to beta, and announce
.
.br
documentation, caching, more robust script support
.
.br
ownership tracking in the registry (no more admin party!)
.
.br
more robust config and option parsing
.
.br
stabilize semver semantics
.
.br
tests
.
.br
update command
.
.br
bundle command
.
.br
Rollback for failed installations
.
.br
Solaris and Cygwin support
.
.IP "\(bu" 4
0\.2
.
.br
First allegedly "stable" release\.
Various fixes found during the Node Knockout extravaganza
.
.br
Minor updates and bugfixes
.
.br
more complete semver functionality
.
.br
Make npm OK to use programmatically (Charlie Robbins)
recursive package removal
.
.br
tab completion (Evan Meagher)
.
.br
shasums on all tarballs
.
.br
explore command: see \fBnpm help explore\fR
.
.br
docs command: see \fBnpm help docs\fR
.
.br
Frequently asked questions at \fBnpm faq\fR
xmas easter egg
.
.br
work with homebrew nodejs
.
.br
Support for \fB"<name>":"<url>"\fR for dependencies\.
.
.IP "\(bu" 4
0\.3
.
.br
More correct permission/uid handling\.  (Sudo now encouraged!)
.
.br
Require node 0\.4\.0
.
.br
Separate semver out into a separate utility\.
.
.br
Packages without "main" modules don\'t export modules\.
.
.br
Remove support for invalid JSON (since node doesn\'t support it)
.
.br
No shims! (Still has symlinks, though)
.
.IP "\(bu" 4
1\.0
.
.br
Simplify configuration greatly\.
.
.br
Install locally (bundle by default)
.
.br
Drastic rearchitecture
.
.IP "" 0

