.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-CHANGELOG" "1" "April 2011" "" ""
.
.SH "NAME"
\fBnpm-changelog\fR \-\- Changes
.
.SH "HISTORY"
.
.IP "\(bu" 4
0\.0
.
.br
Lots of sketches and false starts\.  Abandoned a few times\.
.
.br
Core functionality established\.
.
.IP "\(bu" 4
0\.1
.
.br
push to beta, and announce
.
.br
Solaris and Cygwin support
.
.IP "\(bu" 4
0\.2
.
.br
First allegedly "stable" release\.
.
.br
Most functionality implemented\.
.
.br
Used shim files and \fBname@version\fR symlinks
.
.br
Feature explosion
.
.br
Kind of a mess\.
.
.IP "\(bu" 4
0\.3
.
.br
More correct permission/uid handling when running as root
.
.br
Require node 0\.4\.0
.
.br
Reduce featureset
.
.br
Packages without "main" modules don\'t export modules\.
.
.br
Remove support for invalid JSON (since node doesn\'t support it)
.
.IP "\(bu" 4
1\.0
.
.br
Simplify folder structure greatly\.
.
.br
Install locally (bundle by default)
.
.br
Drastic rearchitecture
.
.IP "" 0

