.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-CONFIG" "1" "October 2010" "" ""
.
.SH "NAME"
\fBnpm-config\fR \-\- Manage the npm configuration file
.
.SH "SYNOPSIS"
.
.nf
npm config set <key> <value> [\-\-global]
npm config get <key>
npm config delete <key>
npm config list
npm config edit
.
.fi
.
.SH "DESCRIPTION"
npm gets its configuration values from 5 sources, in this priority:
.
.IP "\(bu" 4
cli:
The command line flags\.  Putting \fB\-\-foo bar\fR on the command line sets the \fBfoo\fR configuration parameter to \fB"bar"\fR\|\.  A \fB\-\-\fR argument tells the cli
parser to stop reading flags\.  A \fB\-\-flag\fR parameter that is at the \fIend\fR of
the command will be given the value of \fBtrue\fR\|\.
.
.IP "\(bu" 4
env:
Any environment variables that start with \fBnpm_config_\fR will be interpreted
as a configuration parameter\.  For example, putting \fBnpm_config_foo=bar\fR in
your environment will set the \fBfoo\fR configuration parameter to \fBbar\fR\|\.  Any
environment configurations that are not given a value will be given the value
of \fBtrue\fR\|\.  Config values are case\-insensitive, so \fBNPM_CONFIG_FOO=bar\fR will
work the same\.
.
.IP "\(bu" 4
$HOME/\.npmrc (or the \fBuserconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters\.
.
.IP "\(bu" 4
$PREFIX/etc/npmrc (or the \fBglobalconfig\fR param, if set above):
This file is an ini\-file formatted list of \fBkey = value\fR parameters
.
.IP "\(bu" 4
default configs:
This is a set of configuration parameters that are internal to npm, and are
defaults if nothing else is specified\.
.
.IP "" 0
.
.SH "Sub\-commands"
Config supports the following sub\-commands:
.
.SS "set"
.
.nf
npm config set key value
.
.fi
.
.P
Sets the config key to the value\.
.
.SS "get"
.
.nf
npm config get key
.
.fi
.
.P
Echo the config value to stdout\. (NOTE: All the other npm logging is done to
stderr, so pipes should work properly, and you can do \fBnpm get key 2>/dev/null\fR
to print out JUST the config value\.)
.
.SS "list"
.
.nf
npm config list
.
.fi
.
.P
Show all the config settings\.
.
.SS "delete"
.
.nf
npm config delete key
.
.fi
.
.P
Deletes the key from all configuration files\.
.
.SS "edit"
.
.nf
npm config edit
.
.fi
.
.P
Opens the config file in an editor\.  Use the \fB\-\-global\fR flag to edit the global config\.
.
.SH "Config Settings"
npm supports a very basic argument parser\.  For any of the settings
in npm\-config(1), you can set them explicitly for a single command by 
doing:
.
.IP "" 4
.
.nf
npm \-\-key val <command>
.
.fi
.
.IP "" 0
.
.P
Configurations defined on the command line are not saved to the \.npmrc file\.
.
.SS "loglevel"
Default: "info"
.
.P
The log level to show\.
.
.P
Each level maps to a numeric value, above which all logs must pass to be
seen\.  So, setting it to "warn" shows "win", "error" and "warn" messages\.
.
.P
The log levels:
.
.IP "\(bu" 4
silent: Show no output\.  Nothing\.  If there is output on stderr, it\'s
because something is broken\.
.
.IP "\(bu" 4
win: Show the "npm ok" or "npm not ok", but that\'s all\.
.
.IP "\(bu" 4
error: Errors, usually with a stack trace\.
.
.IP "\(bu" 4
warn: Things that you should probably be aware of\.
.
.IP "\(bu" 4
info: Helpful info\.
.
.IP "\(bu" 4
silly: Not\-helpful info\.  (Lots of dumping whole objects and such\.)
.
.IP "" 0
.
.P
Note that output to stdout is always printed\.  This setting just modifies
what\'s logged to stderr\.
.
.SS "auto\-activate"
Default: true
.
.P
Automatically activate a package after installation, if there is not an active
version already\.  Set to "always" to always activate when installing\.
.
.SS "update\-dependents"
Default: true
.
.P
Automatically update a package\'s dependencies after installation, if it is the
newest version installed\. Set to "always" to update dependents when a new
version is installed, even if it\'s not the newest\.
.
.SS "root"
Default: \fB$INSTALL_PREFIX/lib/node\fR
.
.P
The root folder where packages are installed and npm keeps its data\.
.
.SS "binroot"
Default: \fB$INSTALL_PREFIX/bin\fR
.
.P
The folder where executable programs are installed\.
.
.P
Set to "false" to not install executables
.
.SS "manroot"
Default: $INSTALL_PREFIX/share/man
.
.P
The folder where man pages are installed\.
.
.P
Set to "false" to not install man pages\.
.
.SS "registry"
Default: https://registry\.npmjs\.org/
.
.P
The base URL of the npm package registry\.
.
.SS "_auth"
A base\-64 encoded "user:pass" pair\.  This is created by npm\-adduser(1)\.
.
.P
If your config file is ever corrupted, you can set this manually by doing:
.
.IP "" 4
.
.nf
npm adduser
.
.fi
.
.IP "" 0
.
.SS "_authCrypt"
If crypto\.Cipher is available, and you have some private keys in \fB$HOME/\.ssh\fR,
then npm will encrypt your "\fIauth" config before saving to the \.npmrc file,
and will decrypt the "\fRauthCrypt" config when it reads the \.npmrc file\.
.
.SS "tag"
Default: latest
.
.P
If you ask npm to install a package and don\'t tell it a specific version, then
it will install the specified tag\.
.
.P
Note: this has no effect on the npm\-tag(1) command\.
.
.SS "proxy"
If proxy is available, then npm will fetch the modules from the registry via
the proxy server\.
.
.P
Example:
.
.IP "" 4
.
.nf
proxy = http://proxy\-server:8080
.
.fi
.
.IP "" 0
.
.SS "userconfig"
The default user configuration file is process\.env\.HOME+"/\.npmrc"\.
.
.P
Note that this must be provided either in the cli or env settings\. Once the
userconfig is read, it is irrelevant\.
.
.SS "globalconfig"
The default global configuration file is resolved based on the location of the
node executable\. It is process\.execPath+"/\.\./\.\./etc/npmrc"\. In the canonical
NodeJS installation with \fBmake install\fR, this is \fB/usr/local/etc/npmrc\fR\|\. If you
put the node binary somewhere else (for instance, if you are using nvm or
nave), then it would be resolved relative to that location\.
.
.P
Note that this must be provided in the cli, env, or userconfig settings\. Once
the globalconfig is read, this parameter is irrelevant\.
.
.SS "global"
If set to some truish value (for instance, by being the last cli flag or being
passed a literal \fBtrue\fR or \fB1\fR), and the \fBnpm config set\fR param is being
called, then the new configuration paramater is written global config file\.
Otherwise, they are saved to the user config file\.
.
.SS "dev"
If set to a truish value, then it\'ll install the "devDependencies" as well as
"dependencies" when installing a package\.
.
.P
Note that devDependencies are \fIalways\fR installed when linking a package\.
.
.SS "tar"
Default: env\.TAR or "tar"
.
.P
The name of a GNU\-compatible tar program on your system\.
.
.SS "gzip"
Default: env\.GZIPBIN or "gzip"
.
.P
The name of a GNU\-compatible gzip program on your system\.
.
.SS "usage"
If set to \fBtrue\fR, then this will tell help to print out the short usage statement
instead of the long manpage type thing\.
.
.P
This is set automatically if you invoke help like \fBnpm command \-?\fR\|\.
.
.SS "viewer"
Default: "man"
.
.P
The program to use to view help content\.  Set to "woman" to use the emacs troff viewer
by that name\.
