.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-FAQ" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-faq\fR \-\- Frequently Asked Questions
.
.SH "Where can I find these docs in HTML?"
\fIhttps://github\.com/isaacs/npm/tree/master/doc\fR
.
.SH "It didn\'t work\."
That\'s not really a question\.
.
.SH "Why didn\'t it work?"
I don\'t know yet\.
.
.P
Read the error output, and if you can\'t figure out what it means,
do what it says and post a bug with all the information it asks for\.
.
.P
If there doesn\'t seem to be enough output for your liking, run the
command with \fB\-\-loglevel verbose\fR or if you\'re really brave, \fB\-\-loglevel
silly\fR\|\.
.
.SH "How do I make npm less noisy?"
\fBnpm config set loglevel error\fR
.
.P
You can also set it to \fBwin\fR or \fBsilent\fR for even more quietness\.
.
.SH "How do I list installed packages?"
\fBnpm ls installed\fR
.
.P
If you just want to see the names, and not all the registry data, you
can do: \fBnpm ls installed \-\-no\-registry\fR to turn off the registry\.
.
.SH "How do I search for packages?"
\fBnpm ls\fR
.
.P
Arguments are greps\.  \fBnpm ls jsdom\fR shows jsdom packages\.
.
.SH "How do I update npm?"
\fBnpm update npm\fR
.
.P
You can also update all outdated packages by doing \fBnpm update\fR without
any arguments\.
.
.SH "What is a `package`?"
A package is:
.
.IP "\(bu" 4
a) a folder containing a program described by a package\.json file
.
.IP "\(bu" 4
b) a gzipped tarball containing (a)
.
.IP "\(bu" 4
c) a url that resolves to (b)
.
.IP "\(bu" 4
d) a \fB<name>@<version>\fR that is published on the registry with (c)
.
.IP "\(bu" 4
e) a \fB<name>@<tag>\fR that points to (d)
.
.IP "\(bu" 4
f) a \fB<name>\fR that has a "latest" tag satisfying (e)
.
.IP "" 0
.
.P
Even if you never publish your package, you can still get a lot of
benefits of using npm if you just want to write a node program (a), and
perhaps if you also want to be able to easily install it elsewhere
after packing it up into a tarball (b)\.
.
.SH "How do I install node with npm?"
You don\'t\.  Try one of these:
.
.IP "\(bu" 4
\fIhttp://github\.com/isaacs/nave\fR
.
.IP "\(bu" 4
\fIhttp://github\.com/creationix/nvm\fR
.
.IP "" 0
.
.SH "How can I use npm for development?"
See \fBnpm help developers\fR and \fBnpm help json\fR\|\.
.
.P
You\'ll most likely want to \fBnpm link\fR your development folder\.  That\'s
awesomely handy\.
.
.SH "Can I list a url as a dependency?"
No\.
.
.P
If you need to depend on something that isn\'t published, or a package
that is published, but which you\'ve modified slightly, you can do this\.
.
.P
The correct way is to do the following:
.
.IP "\(bu" 4
add a \fB"name":"version"\fR entry to your package\.json file\.
.
.IP "\(bu" 4
\fBnpm bundle install <pkg>\fR where \fB<pkg>\fR is a url or path to your
custom unpublished package\.
.
.IP "" 0
.
.P
When installing your package, npm will skip over any dependencies that
are bundled\.
.
.SH "OK, but can I list a git repo as a dependency?"
No\.
.
.P
Source repositories change quickly\.  That is their purpose\.  Whatever
you bundle into your package is your business, but having the registry
refer to a git URL as a "dependency" defeats the whole purpose\.
.
.P
It\'s possible that something a bit more snazzy will be developed at some
point in the future, but not likely\.  The current system allows for a
lot of use cases, and is very easy to maintain\.
.
.SH "How do I symlink to a dev folder so that I don\'t have to keep re\-installing?"
\fBnpm link\fR
.
.SH "The package registry website\.  What is that exactly?"
See \fBnpm help registry\fR for more info\.
.
.SH "What\'s up with the insecure channel warnings?"
As of this writing, node has problems uploading files over HTTPS\.  That
means that publishes go over HTTP\.
.
.P
Until the problem is solved, npm will complain about being insecure\.
The warnings will disappear when node supports uploading tarballs over
https reliably\.
.
.SH "I forgot my password, and can\'t publish\.  How do I reset it?"
Email \fIi@izs\.me\fR from the email address that you signed up with\.  Then
wait a day or two maybe\.
.
.SH "I get ECONNREFUSED a lot\.  What\'s up?"
Either the registry is down, or node\'s DNS isn\'t able to reach out\.
This happens a lot if you don\'t follow \fIall\fR the steps in the Cygwin
setup doc\.
.
.P
To check if the registry is down, open up \fIhttp://registry\.npmjs\.org/\fR
in a web browser\.  This will also tell you if you are just unable to
access the internet for some reason\.
.
.P
If the registry IS down, let me know by emailing \fIi@izs\.me\fR\|\.  I\'ll have
someone kick it or something\.
.
.SH "Who does npm?"
\fBnpm view npm author\fR
.
.P
\fBnpm view npm contributors\fR
.
.SH "I have a question or request not addressed here\. Where should I put it?"
Discuss it on the mailing list, or post an issue\.
.
.IP "\(bu" 4
\fInpm\-@googlegroups\.com\fR
.
.IP "\(bu" 4
\fIhttp://github\.com/isaacs/npm/issues\fR
.
.IP "" 0
.
.SH "Why does npm hate me?"
npm is not capable of hatred\.  It loves everyone, especially you\.
