.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-INDEX" "1" "September 2011" "" ""
.
.SH "NAME"
\fBnpm-index\fR \-\- Index of all npm documentation
.
.SH "npm help README"
This is just enough info to get you up and running\.
.
.SH "npm help adduser"
Create or verify a user named \fB<username>\fR in the npm registry, and
save the credentials to the \fB\|\.npmrc\fR file\.
.
.SH "npm help bin"
Print the folder where npm will install executables\.
.
.SH "npm help build"
This is the plumbing command called by \fBnpm link\fR and \fBnpm install\fR\|\.
.
.SH "npm help bundle"
The \fBnpm bundle\fR command has been removed in 1\.0, for the simple reason
that it is no longer necessary, as the default behavior is now to
install packages into the local space\.
.
.SH "npm help cache"
Used to add, list, or clear the npm cache folder\.
.
.SH "npm help changelog"
A brief history\.
.
.SH "npm help coding\-style"
npm\'s coding style is a bit unconventional\.  It is not different for
difference\'s sake, but rather a carefully crafted style that is
designed to reduce visual clutter and make bugs more apparent\.
.
.SH "npm help completion"
Enables tab\-completion in all npm commands\.
.
.SH "npm help config"
npm gets its configuration values from 5 sources, in this priority:
.
.SH "npm help deprecate"
This command will update the npm registry entry for a package, providing
a deprecation warning to all who attempt to install it\.
.
.SH "npm help developers"
So, you\'ve decided to use npm to develop (and maybe publish/deploy)
your project\.
.
.SH "npm help docs"
This command tries to guess at the likely location of a package\'s
documentation URL, and then tries to open it using the \fB\-\-browser\fR
config param\.
.
.SH "npm help edit"
Opens the package folder in the default editor (or whatever you\'ve
configured as the npm \fBeditor\fR config \-\- see \fBnpm help config\fR\|\.)
.
.SH "npm help explore"
Spawn a subshell in the directory of the installed package specified\.
.
.SH "npm help faq"
Questions asked frequently\.
.
.SH "npm help folders"
npm puts various things on your computer\.  That\'s its job\.
.
.SH "npm help help\-search"
This command will search the npm markdown documentation files for the
terms provided, and then list the results, sorted by relevance\.
.
.SH "npm help help"
If supplied a topic, then show the appropriate documentation page\.
.
.SH "npm help init"
This will ask you a bunch of questions, and then write a package\.json for you\.
.
.SH "npm help install"
This command installs a package, and any packages that it depends on\.
.
.SH "npm help json"
This document is all you need to know about what\'s required in your package\.json
file\.  It must be actual JSON, not just a JavaScript object literal\.
.
.SH "npm help link"
Package linking is a two\-step process\.
.
.SH "npm help list"
This command will print to stdout all the versions of packages that are
installed, as well as their dependencies, in a tree\-structure\.
.
.SH "npm help npm"
npm is the package manager for the Node JavaScript platform\.  It puts
modules in place so that node can find them, and manages dependency
conflicts intelligently\.
.
.SH "npm help outdated"
This command will check the registry to see if any (or, specific) installed
packages are currently outdated\.
.
.SH "npm help owner"
Manage ownership of published packages\.
.
.SH "npm help pack"
For anything that\'s installable (that is, a package folder, tarball,
tarball url, name@tag, name@version, or name), this command will fetch
it to the cache, and then copy the tarball to the current working
directory as \fB<name>\-<version>\.tgz\fR, and then write the filenames out to
stdout\.
.
.SH "npm help prefix"
Print the prefix to standard out\.
.
.SH "npm help prune"
This command removes "extraneous" packages\.  If a package name is
provided, then only packages matching one of the supplied names are
removed\.
.
.SH "npm help publish"
Publishes a package to the registry so that it can be installed by name\.
.
.SH "npm help rebuild"
This command runs the \fBnpm build\fR command on the matched folders\.  This is useful
when you install a new version of node, and must recompile all your C++ addons with
the new binary\.
.
.SH "npm help registry"
To resolve packages by name and version, npm talks to a registry website
that implements the CommonJS Package Registry specification for reading
package info\.
.
.SH "npm help removing\-npm"
So sad to see you go\.
.
.SH "npm help restart"
This runs a package\'s "restart" script, if one was provided\.
Otherwise it runs package\'s "stop" script, if one was provided, and then
the "start" script\.
.
.SH "npm help root"
Print the effective \fBnode_modules\fR folder to standard out\.
.
.SH "npm help run\-script"
This runs an arbitrary command from a package\'s "scripts" object\.
.
.SH "npm help scripts"
npm supports the "scripts" member of the package\.json script, for the
following scripts:
.
.SH "npm help search"
Search the registry for packages matching the search terms\.
.
.SH "npm help semver"
As a node module:
.
.SH "npm help start"
This runs a package\'s "start" script, if one was provided\.
.
.SH "npm help stop"
This runs a package\'s "stop" script, if one was provided\.
.
.SH "npm help submodule"
If the specified package has a git repository url in its package\.json
description, then this command will add it as a git submodule at \fBnode_modules/<pkg name>\fR\|\.
.
.SH "npm help tag"
Tags the specified version of the package with the specified tag, or the \fB\-\-tag\fR config if not specified\.
.
.SH "npm help test"
This runs a package\'s "test" script, if one was provided\.
.
.SH "npm help uninstall"
This uninstalls a package, completely removing everything npm installed
on its behalf\.
.
.SH "npm help unpublish"
This removes a package version from the registry, deleting its
entry and removing the tarball\.
.
.SH "npm help update"
This command will update all the packages listed to the latest version
(specified by the \fBtag\fR config)\.
.
.SH "npm help version"
Run this in a package directory to bump the version and write the new
data back to the package\.json file\.
.
.SH "npm help view"
This command shows data about a package and prints it to the stream
referenced by the \fBoutfd\fR config, which defaults to stdout\.
.
.SH "npm help whoami"
Print the \fBusername\fR config to standard output\.
