.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-JSON" "1" "October 2010" "" ""
.
.SH "NAME"
\fBnpm-json\fR \-\- Specifics of npm\'s package\.json handling
.
.SH "DESCRIPTION"
npm aims to implement the commonjs Packages \fIhttp://wiki\.commonjs\.org/wiki/Packages/1\.0\fR spec\. However, some
adjustments have been made, which may eventually be unmade, but hopefully will
be incorporated into the spec\.
.
.P
This document is all you need to know about what\'s required in your package\.json
file\.
.
.P
A lot of the behavior described in this document is affected by the config
settings described in \fBnpm help config\fR\|\.
.
.SH "name"
The \fImost\fR important things in your package\.json are the name and version fields\.
.
.P
The name is what your thing is called\.  Some tips:
.
.IP "\(bu" 4
Don\'t put "js" or "node" in the name\.  It\'s assumed that it\'s js, since you\'re
writing a package\.json file, and you can specify the engine using the "engines"
field\.  (See below\.)
.
.IP "\(bu" 4
The name ends up being part of a URL, an argument on the command line, and a
folder name\. So, don\'t use characters that are annoying in those contexts, like
funny UTF things or parentheses or slashes, or else it\'ll break\.
.
.IP "\(bu" 4
The name will probably be passed as an argument to require(), so it should
be something short, but also reasonably descriptive\.
.
.IP "\(bu" 4
You may want to check the npm registry to see if there\'s something by that name
already, before you get too attached to it\.  http://registry\.npmjs\.org/
.
.IP "" 0
.
.SH "version"
The \fImost\fR important things in your package\.json are the name and version fields\.
.
.P
Version must be semver \fIhttp://semver\.org\fR\-compliant\. npm assumes that you\'ve
read the semver page, and that you comply with it\.  Here\'s how it deviates from
what\'s on semver\.org:
.
.IP "\(bu" 4
Versions can start with "v"
.
.IP "\(bu" 4
A numeric item separated from the main three\-number version by a hyphen
will be interpreted as a "build" number, and will \fIincrease\fR the version\.
But, if the tag is not a number separated by a hyphen, then it\'s treated
as a pre\-release tag, and is \fIless than\fR the version without a tag\.
So, 0\.1\.2\-7 > 0\.1\.2\-6 > 0\.1\.2 > 0\.1\.2beta
.
.IP "" 0
.
.P
This is a little bit confusing to explain, but matches what you see in practice
when people create tags in git like "v1\.2\.3" and then do "git describe" to generate
a patch version\.  (This is how node\'s versions are generated, and has driven this
design\.)
.
.SH "description"
Put a description in it\.  It\'s a string\.
.
.SH "homepage"
The url to the project homepage\.
.
.SH "people fields: author, contributors"
The "author" is one person\.  "contributors" is an array of people\.  A "person"
is an object with a "name" field and optionally "url" and "email", like this:
.
.IP "" 4
.
.nf
{ "name" : "Barney Rubble"
, "email" : "b@rubble\.com"
, "url" : "http://barnyrubble\.tumblr\.com/"
}
.
.fi
.
.IP "" 0
.
.P
Or you can shorten that all into a single string, and npm will parse it for you:
.
.IP "" 4
.
.nf
"Barney Rubble <b@rubble\.com> (http://barnyrubble\.tumblr\.com/)
.
.fi
.
.IP "" 0
.
.P
Both email and url are optional either way\.
.
.P
npm also sets a top\-level "maintainers" field with your npm user info\.
.
.SH "main"
The main field is a module ID that is the primary entry point to your program\.
That is, if your package is named \fBfoo\fR, and a user installs it, and then does \fBrequire("foo")\fR, then your main module\'s exports object will be returned\.
.
.P
This should be a module ID relative to the root of your package folder\.
.
.P
For most modules, it makes the most sense to have a main script and often not
much else\.
.
.SH "bin"
A lot of packages have one or more executable files that they\'d like to
install into the PATH\. npm makes this pretty easy (in fact, it uses this
feature to install the "npm" executable\.)
.
.P
To use this, supply a \fBbin\fR field in your package\.json which is a map of
command name to local file name\. On install, npm will link that file into
place right next to wherever node is installed\. (Presumably, this is in your
PATH, and defaults to \fB/usr/local/bin\fR\|\.) On activation, the versioned file
will get linked to the main filename (just like how the main\.js stuff works,
but with an executable in the PATH\.)
.
.P
For example, npm has this:
.
.IP "" 4
.
.nf
{ "bin" : { "npm" : "\./cli\.js" } }
.
.fi
.
.IP "" 0
.
.P
So, when you install npm, it\'ll create a symlink from the \fBcli\.js\fR script to \fB/usr/local/bin/npm\-version\fR\|\. Then, when you activate that version, it\'ll
create a symlink from \fB/usr/local/bin/npm\-version\fR to \fB/usr/local/bin/npm\fR\|\.
.
.P
Shortcut: If you have a single executable, and its name is already what you
want it to be, then you can just supply it as a string\.  For example:
.
.IP "" 4
.
.nf
{ "bin" : "\./path/to/program" }
.
.fi
.
.IP "" 0
.
.P
would be the same as this:
.
.IP "" 4
.
.nf
{ "bin" : { "program" : "\./path/to/program" } }
.
.fi
.
.IP "" 0
.
.SH "modules"
The "modules" member exposes CommonJS modules in the package\. So, if you had a 
package named \fBfoo\fR, and the package\.json contains \fB"modules":{"bar":"\./lib/baz"}\fR, 
and there was a file called \fB\|\./lib/baz\.js\fR, then require("foo/bar") would include 
the module defined in \fB\|\./lib/baz\.js\fR\|\.
.
.P
Subfolders are supported, so you can do this:
.
.IP "" 4
.
.nf
{ "name" : "foo"
, "modules" :
  { "bar/baz" : "\./lib/bar/baz"
  , "quux" : "\./quux"
  }
}
.
.fi
.
.IP "" 0
.
.P
And then, doing \fBrequire("foo/bar/baz")\fR would return the module at \fB\|\./lib/bar/baz\fR
in the foo package\.  Doing \fBrequire("foo/quux")\fR would return the module at \fB\|\./quux\fR in the foo package\.
.
.P
Just like the \fBmain\fR script, the modules linked in this fashion will have their
dependencies and paths set up properly by npm\. (In fact, "main" is just sugar
around setting a module named "index"\.)
.
.SH "man"
Specify either a single file or an array of filenames to put in place for the \fBman\fR program to find\.
.
.P
If only a single file is provided, then it\'s installed such that it is the
result from \fBman <pkgname>\fR, regardless of its actual filename\.  For example:
.
.IP "" 4
.
.nf
{ "name" : "foo"
, "man" : "\./man/doc\.1"
}
.
.fi
.
.IP "" 0
.
.P
would link the \fB\|\./man/doc\.1\fR file in such that it is the target for \fBman foo\fR
.
.P
If the filename doesn\'t start with the package name, then it\'s prefixed\.
So, this:
.
.IP "" 4
.
.nf
{ "name" : "foo"
, "man" : [ "\./man/foo\.1", "\./man/bar\.1" ]
}
.
.fi
.
.IP "" 0
.
.P
will create files to do \fBman foo\fR and \fBman foo\-bar\fR\|\.
.
.P
Man files must end with a number, and optionally a \fB\|\.gz\fR suffix if they are
compressed\.  The number dictates which man section the file is installed into\.
.
.IP "" 4
.
.nf
{ "name" : "foo"
, "man" : [ "\./man/foo\.1", "\./man/foo\.2" ]
}
.
.fi
.
.IP "" 0
.
.P
will create entries for \fBman foo\fR and \fBman 2 foo\fR
.
.SH "directories"
The CommonJS Packages \fIhttp://wiki\.commonjs\.org/wiki/Packages/1\.0\fR spec details a
few ways that you can indicate the structure of your package using a \fBdirectories\fR
hash\. If you look at npm\'s package\.json \fIhttp://registry\.npmjs\.org/npm/latest\fR,
you\'ll see that it has directories for doc, lib, and man\.
.
.P
In the future, this information may be used in other creative ways\.
.
.SS "directories\.lib"
If you specify a "lib" directory, and do not supply a modules hash, then the lib
folder will be walked and any \fI\|\.js or \fR\|\.node files found will be exposed as a
default module hash\.
.
.P
Providing an explicit modules hash is encouraged over exposing the entire lib
folder\.
.
.SS "directories\.bin"
If you specify a "bin" directory, then all the files in that folder will be used
as the "bin" hash\.
.
.P
If you have a "bin" hash already, then this has no effect\.
.
.SS "directories\.man"
A folder that is full of man pages\.  Sugar to generate a "man" array by walking the folder\.
.
.SS "directories\.doc"
Put markdown files in here\.  Eventually, these will be displayed nicely, maybe, someday\.
.
.SS "directories\.example"
Put example scripts in here\.  Someday, it might be exposed in some clever way\.
.
.SH "repository"
Specify the place where your code lives\. This is helpful for people who want to
contribute, as well as perhaps maybe being the underpinning of some magical "track
this package on git" feature someday maybe if somebody wants to write it ever\.
.
.P
Do it like this:
.
.IP "" 4
.
.nf
"repository" :
  { "type" : "git"
  , "url" : "http://github\.com/isaacs/npm\.git"
  }
"repository" :
  { "type" : "svn"
  , "url" : "http://v8\.googlecode\.com/svn/trunk/"
  }
.
.fi
.
.IP "" 0
.
.P
The URL should be a publicly available (perhaps read\-only) url that can be handed
directly to a VCS program without any modification\.  It should not be a url to an
html project page that you put in your browser\.  It\'s for computers\.
.
.P
Here are some examples of Doing It Wrong:
.
.IP "" 4
.
.nf
WRONG!
"repository" :
  { "type" : "git"
  , "url" : "git@github\.com:isaacs/npm\.git" <\-\- THIS IS PRIVATE!
  }
ALSO WRONG!
"repository" :
  { "type" : "git"
  , "url" : "http://github\.com/isaacs/npm" <\-\- THIS IS WEBPAGE!
  }
This is ok, but completely unnecessary:
"repository" :
  { "type" : "git"
  , "url" : "http://github\.com/isaacs/npm\.git"
  , "private" : "git@github\.com:isaacs/npm\.git"
  , "web" : "http://github\.com/isaacs/npm"
  }
.
.fi
.
.IP "" 0
.
.SH "scripts"
The "scripts" member is an object hash of script commands that are run
at various times in the lifecycle of your package\.  The key is the lifecycle
event, and the value is the command to run at that point\.
.
.P
See \fBnpm help scripts\fR to find out more about writing package scripts\.
.
.SH "dependencies"
Dependencies are specified with a simple hash of package name to version
range\. The version range is EITHER a string with has one or more
space\-separated descriptors, OR a range like "fromVersion \- toVersion"
.
.P
Version range descriptors may be any of the following styles, where "version"
is a semver compatible version identifier\.
.
.IP "\(bu" 4
\fBversion\fR Must match \fBversion\fR exactly
.
.IP "\(bu" 4
\fB=version\fR Same as just \fBversion\fR
.
.IP "\(bu" 4
\fB>version\fR Must be greater than \fBversion\fR
.
.IP "\(bu" 4
\fB>=version\fR etc
.
.IP "\(bu" 4
\fB<version\fR
.
.IP "\(bu" 4
\fB<=version\fR
.
.IP "\(bu" 4
\fB*\fR Matches any version
.
.IP "\(bu" 4
\fB""\fR (just an empty string) Same as \fB*\fR
.
.IP "\(bu" 4
\fBversion1 \- version2\fR Same as \fB>=version1 <=version2\fR\|\.
.
.IP "\(bu" 4
\fBrange1 || range2\fR Passes if either range1 or range2 are satisfied\.
.
.IP "" 0
.
.P
For example, these are all valid:
.
.IP "" 4
.
.nf
{ "dependencies" :
  { "foo" : "1\.0\.0 \- 2\.9999\.9999"
  , "bar" : ">=1\.0\.2 <2\.1\.2"
  , "baz" : ">1\.0\.2 <=2\.3\.4"
  , "boo" : "2\.0\.1"
  , "qux" : "<1\.0\.0 || >=2\.3\.1 <2\.4\.5 || >=2\.5\.2 <3\.0\.0"
  }
}
.
.fi
.
.IP "" 0
.
.SH "engines"
Packages/1\.0 says that you can have an "engines" field with an array of engine
names\. However, it has no provision for specifying which version of the engine
your stuff runs on\.
.
.P
With npm, you can use either of the following styles to specify the version of
node that your stuff works on:
.
.IP "" 4
.
.nf
{ "engines" : [ "node >=0\.1\.27 <0\.1\.30" ] }
.
.fi
.
.IP "" 0
.
.P
or:
.
.IP "" 4
.
.nf
{ "engines" : { "node" : ">=0\.1\.27 <0\.1\.30" } }
.
.fi
.
.IP "" 0
.
.P
And, like with dependencies, if you don\'t specify the version (or if you
specify "*" as the version), then any version of node will do\.
.
.P
If you specify an "engines" field, then npm will require that "node" be
somewhere on that list\. If "engines" is omitted, then npm will just assume
that it works on node\.
.
.SH "overlay"
npm responds to the \fBnode\fR and \fBnpm\fR env\-specific package\.json values, which
you can hang on the "overlay" key\.
.
.P
For example:
.
.IP "" 4
.
.nf
{ "name" : "foo"
, "version" : 7
, "description" : "generic description"
, "overlay" :
  { "node" :
    { "name" : "bar"
    , "description" : "description for node"
    }
  , "npm" :
    { "version" : "1\.0\.7"
    , "description" : "description for npm"
    }
  , "narwhal" :
    { "description" : "description for narwhal" }
  }
}
.
.fi
.
.IP "" 0
.
.P
In this case, this is what npm will treat it as:
.
.IP "" 4
.
.nf
{ "name" : "bar"
, "version" : "1\.0\.7"
, "description" : "description for npm"
}
.
.fi
.
.IP "" 0
.
.P
This way, even if npm is not exactly the same as some other package management
system, you can still use both, and it can be a happy planet\.
