.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-LINK" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-link\fR \-\- Symlink a package folder
.
.SH "SYNOPSIS"
.
.nf
npm link <folder>
.
.fi
.
.SH "DESCRIPTION"
This will link a source folder into npm\'s registry using a symlink, and then
build it according to the package\.json file in that folder\'s root\. This is
handy for installing your own stuff, so that you can work on it and test it
iteratively without having to continually rebuild\.
.
.SH "Linked Package Version"
When linking a package folder, npm doesn\'t use the version in the
package\.json file\.  Instead, it creates a "fake" version number of:
.
.IP "" 4
.
.nf
"9999\.0\.0\-LINK\-" + hash(folder)
.
.fi
.
.IP "" 0
.
.P
This way, linking the same folder will always result in the same version
number, even if you bump the version in the package\.json file\.  The
extremely high major version ensures that it will always be considered
the "highest" version, since it is a development bleeding\-edge thing\.
.
.SH "CONFIGURATION"
See the config section of \fBnpm help install\fR\|\.  The \fBdev\fR configuration
setting is always set to \fBtrue\fR when doing a link install\.
