.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-OUTDATED" "1" "October 2010" "" ""
.
.SH "NAME"
\fBnpm-outdated\fR \-\- Check for outdated packages
.
.SH "SYNOPSIS"
.
.nf
npm outdated [<pkg> [<pkg> \.\.\.]]
.
.fi
.
.SH "DESCRIPTION"
This command will check the registry to see if any (or, specific) installed
packages are currently outdated\.
