.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-RUN\-SCRIPT" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-run-script\fR \-\- Run arbitrary package scripts
.
.SH "SYNOPSIS"
.
.nf
npm run\-script <script> <name>
.
.fi
.
.SH "DESCRIPTION"
This runs an arbitrary command from a package\'s "scripts" object\.
.
.P
It is used by the test, start, restart, and stop commands, but can be
called directly, as well\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
npm\-scripts(1)
.
.IP "\(bu" 4
npm\-test(1)
.
.IP "\(bu" 4
npm\-start(1)
.
.IP "\(bu" 4
npm\-restart(1)
.
.IP "\(bu" 4
npm\-stop(1)
.
.IP "" 0

