.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-SEARCH" "1" "May 2011" "" ""
.
.SH "NAME"
\fBnpm-search\fR \-\- Search for packages
.
.SH "SYNOPSIS"
.
.nf
npm search [search terms \.\.\.]
.
.fi
.
.SH "DESCRIPTION"
Search the registry for packages matching the search terms\.
