.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-START" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-start\fR \-\- Start a package
.
.SH "SYNOPSIS"
.
.nf
npm start <name>[@<version>] [<name>[@<version>] \.\.\.]
.
.fi
.
.SH "DESCRIPTION"
This runs a package\'s "start" script, if one was provided\.
.
.P
If no version is specified, then it starts the "active" version\.
