.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-TAG" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-tag\fR \-\- Tag a published version
.
.SH "SYNOPSIS"
.
.nf
npm tag packagename@1\.2\.3 tagname
.
.fi
.
.SH "DESCRIPTION"
Tags the specified version of "packagename" with the specified "tagname"\.
.
.P
The only tags with special significance are "stable", which is the version
that gets installed by default when no other tag or version number is
specified, and "latest", which always points to the most recently uploaded
version of a package\.
