.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-TAG" "1" "November 2010" "" ""
.
.SH "NAME"
\fBnpm-tag\fR \-\- Tag a published version
.
.SH "SYNOPSIS"
.
.nf
npm tag <name>@<version> <tagname>
.
.fi
.
.SH "DESCRIPTION"
Tags the specified version of the package with the specified "tagname"\.
.
.P
The only tag with special significance is "latest"\.  That version is
installed by default when no other tag or version number is specified,
and always points to the most recently updated version of a package\.
