.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-TAG" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-tag\fR \-\- Tag a published version
.
.SH "SYNOPSIS"
.
.nf
npm tag <name>@<version> [<tag>]
.
.fi
.
.SH "DESCRIPTION"
Tags the specified version of the package with the specified tag, or the \fB\-\-tag\fR config if not specified\.
