.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-TEST" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-test\fR \-\- Test a package
.
.SH "SYNOPSIS"
.
.nf
  npm test <name>[@<version>] [<name>[@<version>] \.\.\.]
.
.fi
.
.SH "DESCRIPTION"
This runs a package\'s "test" script, if one was provided\.
.
.P
If no version is specified, then it tests the "active" version\.
