.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-UNPUBLISH" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-unpublish\fR \-\- Remove a package from the registry
.
.SH "SYNOPSIS"
.
.nf
npm unpublish <name>[@<version>]
.
.fi
.
.SH "DESCRIPTION"
This removes a package version from the registry, deleting its
entry and removing the tarball\.
.
.P
If no version is specified, or if all versions are removed then
the root package entry is removed from the registry entirely\.
