.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-UPDATE" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-update\fR \-\- Update a package
.
.SH "SYNOPSIS"
.
.nf
npm update [<name> [<name> \.\.\.]]
.
.fi
.
.SH "DESCRIPTION"
This command will update all the packages listed to the latest version
(specified by the \fBtag\fR config)\.
.
.P
It will also install missing packages\.
