.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-VERSION" "1" "March 2011" "" ""
.
.SH "NAME"
\fBnpm-version\fR \-\- Bump a package version
.
.SH "SYNOPSIS"
.
.nf
npm version <newversion>
.
.fi
.
.SH "DESCRIPTION"
Run this in a package directory to bump the version and write the new
data back to the package\.json file\.
.
.P
If run in a git repo, it will also create a version commit and tag, and
fail if the repo is not clean\.
