.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-VIEW" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-view\fR \-\- View registry info
.
.SH "SYNOPSIS"
.
.nf
npm view [<pkg> [<pkg> \.\.\.]]
.
.fi
.
.SH "DESCRIPTION"
This command just spits out the data that is on the npm registry for a given
package or packages\.
.
.P
You could also go to the registry url directly in your web browser to see the
same information\.
