.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "ACTIVATE" "1" "September 2010" "" ""
.
.SH "NAME"
\fBactivate\fR \-\- Activate an installed version of a package
.
.SH "SYNOPSIS"
.
.nf
npm activate <name>@<version> [<name>@<version> \.\.\.]
.
.fi
.
.SH "DESCRIPTION"
This "activates" a specific version of a package, so that you can just do \fBrequire("foo")\fR without having to specify the version\.
.
.SH "SEE ALSO"
npm\-deactivate(1)
