.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ACTIVATE" "1" "May 2010" "" ""
.
.SH "NAME"
\fBactivate\fR \- Activate an installed version of a package
.
.SH "SYNOPSIS"
.
.nf

npm activate <name> <version>
.
.fi
.
.SH "DESCRIPTION"
This "activates" a specific version of a package, so that you can just do \fBrequire("foo")\fR without having to specify the version\.
.
.SH "SEE ALSO"
npm\-deactivate(1)
