.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-ADDUSER" "1" "July 2010" "" ""
.
.SH "NAME"
\fBnpm\-adduser\fR \- Add a registry user account
.
.SH "SYNOPSIS"
.
.nf

npm adduser <username> <password> <email>
.
.fi
.
.SH "DESCRIPTION"
Create a user named \fB<username>\fR in the npm registry, and save the credentials to the \fB\.npmrc\fR file\. Note that this leaves the password in your \fB\.bash_history\fR, and it is currently stored in the clear in the config file\. So, don\'t use a password you care too much about\.
.
.P
For now, if you somehow break your \fB\.npmrc\fR file, and have forgotten your password, you\'re boned\. Send an email to i@izs\.me and I\'ll delete the record from the registry so that you can re\-add it\.
.
.P
If you break your \fB\.npmrc\fR file, but you remember your password, you can put your user auth back by using the \fBbase64\fR program like so:
.
.IP "" 4
.
.nf

npm config set auth $( echo \-n user:pass | base64 )
.
.fi
.
.IP "" 0
.
.P
Install base64 using whichever method you normally use to put programs on your computer\. (apt\-get, homebrew, macports, yum, or just download the code and build it yourself\.)
.
.P
Or bug me to to remove your account, and then recreate it\.
