.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-CACHE" "1" "May 2010" "" ""
.
.SH "NAME"
\fBnpm\-cache\fR \- install a package
.
.SH "SYNOPSIS"
.
.nf

npm cache add <tarball file>
npm cache add <folder>
npm cache add <tarball url>
npm cache add <name> <version>

npm cache ls [<path>]

npm cache clean [<pkg> [<version>]]
.
.fi
.
.SH "DESCRIPTION"
.
.TP
add
Access the local cache of package data\. This command is primarily intended to be used internally by npm, but it can provide a way to add data to the local installation cache explicitly\.
.
.IP
If two arguments are provided, then npm will fetch the data from the registry\. This allows npm to use the filesystem as a local proxy to the registry\.
.
.TP
ls
Show the data in the cache\. Additional arguments are joined together in a path\-like fashion, but something like \fBnpm cache ls npm/0\.1\.5\fR is acceptable as well\.
.
.TP
clean
Delete data out of the cache for a specific package and version, all versions of a package, or all data for all packages, depending on the arguments supplied\.
.
.IP
This can be used if invalid data gets into the cache\.
.
.SH "DETAILS"
npm stores data for a version of a package in \fB$ROOT/\.npm/\.cache/<name>/<version>\fR\. Three pieces of data are stored in this folder:
.
.TP
package/
A folder containing the package contents as they appear in the tarball\.
.
.TP
package\.json
The package\.json file, as npm sees it, with overlays applied and a _id attribute\.
.
.TP
package\.tgz
The tarball for that version\.
.
.SH "HISTORY"
Added in npm version 0\.1\.6
