.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-DEACTIVATE" "1" "May 2010" "" ""
.
.SH "NAME"
\fBnpm\-deactivate\fR \- Deactivate the active version of a package
.
.SH "SYNOPSIS"
.
.nf

npm deactivate <name>
.
.fi
.
.SH "DESCRIPTION"
If there\'s an active version of the package, this will unlink it from that preferential position\.
.
.SH "SEE ALSO"
npm\-activate(1)
