.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-HELP" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-help\fR \-\- Get help about npm commands
.
.SH "SYNOPSIS"
.
.nf
npm help <section>
.
.fi
.
.SH "DESCRIPTION"
\fB<section>\fR is one of:
activate
adduser
build
bundle
cache
coding\-style
config
deactivate
developers
folders
future\-ideas/deploy
future\-ideas/remote
future\-ideas/site
help
install
json
link
list
ln
ls
npm
owner
publish
rebuild
restart
rm
scripts
start
stop
tag
test
uninstall
unpublish
update
view
.
.SH "12\-second Intro"
You probably got npm because you want to install stuff\.
.
.P
Use \fBnpm install blerg\fR to install the latest version of "blerg"\.  Check out \fBnpm help install\fR for more info\.  It can do a lot of stuff\.
.
.P
Use the \fBnpm ls\fR command to show everything that\'s available\.  Looking for
express\-related modules?  \fBnpm ls express\fR\|\.  Looking for the latest express? \fBnpm ls express latest\fR\|\.  (The arguments are just simple greps\.)  And of course, \fBnpm help ls\fR will tell you more\.
.
.P
Use \fBnpm ls installed\fR to show everything you\'ve installed\.
.
.SH "Where to go for help"
Come bug isaacs in irc://freenode\.net#node\.js\.  He\'ll ask you to copy the npm
output to a pastie or gist, and perhaps to post an issue if it\'s a new bug\.
.
.P
Failing that, report the issue:
.
.IP "\(bu" 4
web: \fIhttp://github\.com/isaacs/npm/issues\fR
.
.IP "\(bu" 4
email: \fInpm\-@googlegroups\.com\fR
.
.IP "" 0
.
.P
If you ask something that\'s answered by this doc, you may be told to RTFM\.
So, save yourself some time and read it now\.
.
.SH "Configs"
Use the \fBnpm config\fR command to manage how npm does stuff and where it puts things\.
It stores your configs in the \fB~/\.npmrc\fR file\.  Check \fBnpm help config\fR for more
info on that, if you care\.
.
.P
You can override any config for just a single command by doing \fB\-\-configname value\fR
on the command line\.
.
.SH "Developers"
If you\'re using npm to develop and publish your code, check out the following topics:
.
.IP "\(bu" 4
json:
Make a package\.json file\.  The "json" help doc will tell you what to put in it\.
.
.IP "\(bu" 4
link:
For linking your current working code into Node\'s path, so that you don\'t have to
reinstall every time you make a change\.  Use "npm link" to do this\.
.
.IP "\(bu" 4
install:
It\'s a good idea to install things if you don\'t need the symbolic link\.  Especially,
installing other peoples code from the registry is done via "npm install"\.
.
.IP "\(bu" 4
adduser:
Use the \fBnpm adduser\fR command to add a user account for the npm registry, or to
authorize yourself on a new machine\.  If you forget your password, send an email
to \fInpm\-@googlegroups\.com\fR and we\'ll delete your account so you can recreate it\.
.
.IP "\(bu" 4
publish:
Use the \fBnpm publish\fR command to upload your code to the registry, so that other
people can install it easily\.
.
.IP "" 0
.
.SH "Contributing"
Patches welcome!
.
.IP "\(bu" 4
code:
Read through \fBnpm help coding\-style\fR if you plan to submit code\.  You don\'t have to
agree with it, but you do have to follow it\.
.
.IP "\(bu" 4
docs:
If you find an error in the documentation, edit the appropriate markdown file in the
"doc" folder\.  If you have the "ronn" gem installed, then you can \fBmake doc\fR to build
the man page, but this is not necessary for your patch to be accepted\.
.
.IP "\(bu" 4
tests:
The tests are pretty limited\.  It would be great to perhaps use
something like expresso or vows\.
.
.IP "" 0
.
.P
Contributors are listed in npm\'s \fBpackage\.json\fR file\.
