.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-PUBLISH" "1" "May 2010" "" ""
.
.SH "NAME"
\fBnpm\-publish\fR \- Publish a package
.
.SH "SYNOPSIS"
.
.nf

npm publish <tarball>
npm publish <folder>
.
.fi
.
.SH "DESCRIPTION"
Publishes a package to the registry so that it can be installed by name\.
.
.TP
\fB<folder>\fR
A folder containing a package\.json file
.
.TP
\fB<tarball>\fR
A url or file path to a gzipped tar archive containing a single folder with a package\.json file inside\.
.
.P
Fails if the package name and version combination already exists in the registry\.
