.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "NPM\-PUBLISH" "1" "April 2010" "" ""
.
.SH "NAME"
\fBnpm\-publish\fR \-\- Publish a package
.
.SH "SYNOPSIS"
.
.nf
npm publish <tarball\-url>
.
.fi
.
.SH "DESCRIPTION"
Publishes a tarball containing a package to the npm registry.
.
.P
When installation from the registry is supported, this will be much more
relevant.
