.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-UNINSTALL" "1" "May 2010" "" ""
.
.SH "NAME"
\fBnpm\-uninstall\fR \- Remove a package
.
.SH "SYNOPSIS"
.
.nf

npm uninstall <name> [<version>]
npm rm <name> [<version>]
.
.fi
.
.SH "DESCRIPTION"
This uninstalls a package, completely removing everything installed for it\. If it\'s currently active, then it will be deactivated first, unless the \fBauto\-deactivate\fR config setting is set to "false"\. If anything is depending on it, then those must be uninstalled first\.
.
.P
If the version is omitted, then all versions of a package are removed\.
