.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-STOP" "1" "September 2010" "" ""
.
.SH "NAME"
\fBnpm-stop\fR \-\- Stop a package
.
.SH "SYNOPSIS"
.
.nf
npm stop <name>[@<version>] [<name>[@<version>] \.\.\.]
.
.fi
.
.SH "DESCRIPTION"
This runs a package\'s "stop" script, if one was provided\.
.
.P
If no version is specified, then it stops the "active" version\.
