.\" generated with Ronn/v0.4.1
.\" http://github.com/rtomayko/ronn/
.
.TH "NPM\-TAG" "1" "April 2010" "" ""
.
.SH "NAME"
\fBnpm\-tag\fR \-\- Tag a published version
.
.SH "SYNOPSIS"
.
.nf
npm tag packagename 1.2.3 tagname
.
.fi
.
.SH "DESCRIPTION"
Tags the specified version of "packagename" with the specified "tagname".
.
.P
The only tag with any special significance is "stable".
.
.P
When installation from the registry is supported, this will be much more
relevant.
