.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NPM\-UNPUBLISH" "1" "June 2010" "" ""
.
.SH "NAME"
\fBnpm\-unpublish\fR \- Remove a package from the registry
.
.SH "SYNOPSIS"
.
.nf

npm unpublish <name> <version>
.
.fi
.
.SH "DESCRIPTION"
This removes a package version from the registry, deleting its entry and removing the tarball\.
