language: node_js
node_js:
  - "0.11"
  - "0.10"
env:
  - DEPLOY_VERSION=testing
before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "sudo mkdir -p /var/run/couchdb"
  - git config --global user.email "travis@npmjs.org"
  - git config --global user.name "NPM Travis-CI"
script: "npm run-script tap"
