
module.exports = writeShim
writeShim.ifExists = shimIfExists

var fs = require("./graceful-fs")
  , path = require("path")
  , relativize = require("./relativize")
  , mkdir = require("./mkdir-p")
  , log = require("./log")

function shimIfExists (from, to, deps, cb) {
  if (!cb) cb = deps, deps = false
  fs.stat(from, function (er) {
    if (er) return cb()
    writeShim(from, to, deps, cb)
  })
}

function writeShim (from, to, deps, cb) {
  if (!cb) cb = deps, deps = false
  log.silly([from,to], "writeShim")
  if (deps) {
    deps = deps.filter(function (d) { return d }).map(function (dep) {
      return relativize(dep, to)
    })
  }
  from = relativize(from, to).replace(/\.(js|node)$/, '')
  // todo: remove this deps juggling somehow.
  var code = "#!/usr/bin/env node\n"
           + "// generated by npm, please don't touch!\n"
           + ( deps ? "var deps = " + JSON.stringify(deps || []) + "\n"
                    + "  , path = require('path')\n"
                    + "deps = deps.map(function (dep, i, deps) {\n"
                    + "  return require('path').join(__dirname, dep)\n"
                    + "}).filter(function (dep, i, deps) {\n"
                    + "  return -1 !== require.paths.indexOf(dep)\n"
                    + "})\n"
                    : "" )
           + "require.paths.unshift.apply(require.paths, deps)\n"
           + "module.exports = require("+JSON.stringify(from)+")\n"
           + ( deps ? "deps.forEach(function (dep, i, deps) {\n"
                    + "  var met = require.paths.indexOf(dep)\n"
                    + "  if (met !== -1) {\n"
                    + "    require.paths.splice(met, 1)\n"
                    + "  }\n"
                    + "})\n"
                    : "" )

  mkdir(path.dirname(to), function (er) {
    if (er) return cb(er)
    fs.writeFile(to, code, "ascii", function (er, ok) {
      if (er) return cb(er)
      fs.chmod(to, 0755, cb)
    })
  })
}
