
module.exports = writeShim
writeShim.ifExists = shimIfExists

var fs = require("fs")
  , path = require("path")
  , relativize = require("./relativize")

function shimIfExists (from, to, dep, cb) {
  if (!cb) cb = dep, dep = false
  fs.stat(from, function (er) {
    if (er) return cb()
    writeShim(from, to, dep, cb)
  })
}

function writeShim (from, to, dep, cb) {
  if (!cb) cb = dep, dep = false
  if (dep) dep = JSON.stringify(relativize(dep, to))
  from = JSON.stringify(relativize(from, to).replace(/\.(js|node)$/, ''))
  var nodePath = process.execPath
               || path.join(process.installPrefix, "bin", "node")
    , code = "#!"+nodePath+"\n"
           + "// generated by npm, please don't touch!\n"
           + (dep ? "var depMet = require.paths.indexOf("+dep+") !== -1\n"
                  + "if (!depMet) require.paths.unshift("+dep+")\n"
             : ""
             )
           + "module.exports = require(" + from + ")\n"
           + ( dep ? "if (!depMet) {\n" // get the possibly-changed location
                   + "  var i = require.paths.indexOf("+dep+")\n"
                   + "  if (i !== -1) require.paths.splice(i, 1)\n"
                   + "}"
             : "\n"
             )
  fs.writeFile(to, code, "ascii", function (er, ok) {
    if (er) return cb(er)
    fs.chmod(to, 0755, cb)
  })
}
