.\" Generated with Ronnjs/v0.1
.\" http://github.com/kapouer/ronnjs/
.
.TH "NPM\-COMMANDS" "3" "August 2011" "" ""
.
.SH "NAME"
\fBnpm-commands\fR \-\- npm commands
.
.SH "SYNOPSIS"
.
.nf
npm\.commands\.<command>(args, callback)
.
.fi
.
.SH "DESCRIPTION"
npm comes with a full set of commands, and each of the commands takes a
similar set of arguments\.
.
.P
In general, all commands on the command object take an \fBarray\fR of positional
argument \fBstrings\fR\|\. The last argument to any function is a callback\. Some
commands are special and take other optional arguments\.
.
.P
All commands have their own man page\. See \fBman npm\-<command>\fR for command\-line
usage, or \fBman 3 npm\-<command>\fR for programmatic usage\.
.
.SH "COMMANDS"
.
.SS "install"
Install a package\.
.
.IP "\(bu" 4
"install"
.
.IP "\(bu" 4
"uninstall"
"cache"
.
.IP "\(bu" 4
"config"
.
.IP "\(bu" 4
"set"
.
.IP "\(bu" 4
"get"
.
.IP "\(bu" 4
"update"
.
.IP "\(bu" 4
"outdated"
.
.IP "\(bu" 4
"prune"
.
.IP "\(bu" 4
"submodule"
.
.IP "\(bu" 4
"pack"
.
.IP "\(bu" 4
"rebuild"
.
.IP "\(bu" 4
"link"
.
.IP "\(bu" 4
"publish"
.
.IP "\(bu" 4
"tag"
"adduser"
.
.IP "\(bu" 4
"unpublish"
.
.IP "\(bu" 4
"owner"
.
.IP "\(bu" 4
"deprecate"
.
.IP
"help"
.
.IP "\(bu" 4
"help\-search"
.
.IP "\(bu" 4
"ls"
.
.IP "\(bu" 4
"search"
.
.IP "\(bu" 4
"view"
.
.IP "\(bu" 4
"init"
.
.IP "\(bu" 4
"version"
.
.IP "\(bu" 4
"edit"
.
.IP "\(bu" 4
"explore"
.
.IP "\(bu" 4
"docs"
"faq"
.
.IP "\(bu" 4
"root"
.
.IP "\(bu" 4
"prefix"
.
.IP "\(bu" 4
"bin"
.
.IP "\(bu" 4
"whoami"
.
.IP "\(bu" 4
"test"
.
.IP "\(bu" 4
"stop"
.
.IP "\(bu" 4
"start"
.
.IP "\(bu" 4
"restart"
.
.IP "\(bu" 4
"run\-script"
"completion"
.
.IP "" 0

